project:
  type: website
  output-dir: docs

website:
  title: "Brandon_Meyer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      

format:
  html:
    grid: 
      body-width: 1200px
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual

